-- Migration: add name_en column to ingredients table
-- Run this in Supabase Dashboard → SQL Editor

ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS name_en TEXT;

UPDATE ingredients SET name_en = CASE name
  -- Meat
  WHEN 'Курица'            THEN 'Chicken'
  WHEN 'Говядина'          THEN 'Beef'
  WHEN 'Свинина'           THEN 'Pork'
  WHEN 'Фарш'              THEN 'Minced meat'
  WHEN 'Сосиски'           THEN 'Sausages'
  -- Cereals
  WHEN 'Макароны'          THEN 'Pasta'
  WHEN 'Гречка'            THEN 'Buckwheat'
  WHEN 'Рис'               THEN 'Rice'
  WHEN 'Овсянка'           THEN 'Oatmeal'
  -- Vegetables
  WHEN 'Лук'               THEN 'Onion'
  WHEN 'Морковь'           THEN 'Carrot'
  WHEN 'Помидоры'          THEN 'Tomatoes'
  WHEN 'Картофель'         THEN 'Potato'
  WHEN 'Перец болгарский'  THEN 'Bell pepper'
  WHEN 'Чеснок'            THEN 'Garlic'
  WHEN 'Огурцы'            THEN 'Cucumber'
  WHEN 'Капуста'           THEN 'Cabbage'
  WHEN 'Кабачки'           THEN 'Zucchini'
  WHEN 'Баклажаны'         THEN 'Eggplant'
  WHEN 'Свекла'            THEN 'Beetroot'
  WHEN 'Редис'             THEN 'Radish'
  WHEN 'Укроп'             THEN 'Dill'
  WHEN 'Петрушка'          THEN 'Parsley'
  WHEN 'Шпинат'            THEN 'Spinach'
  WHEN 'Брокколи'          THEN 'Broccoli'
  WHEN 'Цветная капуста'   THEN 'Cauliflower'
  WHEN 'Лук зеленый'       THEN 'Spring onion'
  WHEN 'Сельдерей'         THEN 'Celery'
  WHEN 'Тыква'             THEN 'Pumpkin'
  -- Dairy
  WHEN 'Молоко'            THEN 'Milk'
  WHEN 'Сыр'               THEN 'Cheese'
  WHEN 'Сметана'           THEN 'Sour cream'
  WHEN 'Яйца'              THEN 'Eggs'
  WHEN 'Масло сливочное'   THEN 'Butter'
  -- Spices
  WHEN 'Соль'              THEN 'Salt'
  WHEN 'Перец черный'      THEN 'Black pepper'
  WHEN 'Лавровый лист'     THEN 'Bay leaf'
  WHEN 'Паприка'           THEN 'Paprika'
  WHEN 'Кориандр'          THEN 'Coriander'
  WHEN 'Тмин'              THEN 'Cumin'
  WHEN 'Куркума'           THEN 'Turmeric'
  WHEN 'Имбирь'            THEN 'Ginger'
  WHEN 'Орегано'           THEN 'Oregano'
  WHEN 'Базилик'           THEN 'Basil'
  WHEN 'Тимьян'            THEN 'Thyme'
  WHEN 'Розмарин'          THEN 'Rosemary'
  WHEN 'Мускатный орех'    THEN 'Nutmeg'
  WHEN 'Корица'            THEN 'Cinnamon'
  WHEN 'Гвоздика'          THEN 'Cloves'
  WHEN 'Ваниль'            THEN 'Vanilla'
  WHEN 'Карри'             THEN 'Curry'
  WHEN 'Перец чили'        THEN 'Chili pepper'
  WHEN 'Красный перец'     THEN 'Red pepper'
  WHEN 'Горчица'           THEN 'Mustard'
  WHEN 'Уксус'             THEN 'Vinegar'
  WHEN 'Лимонный сок'      THEN 'Lemon juice'
  WHEN 'Цедра лимона'      THEN 'Lemon zest'
  WHEN 'Хмели-сунели'      THEN 'Khmeli-suneli'
  WHEN 'Укроп сушёный'     THEN 'Dried dill'
  WHEN 'Мята'              THEN 'Mint'
  WHEN 'Кунжут'            THEN 'Sesame'
  WHEN 'Кунжутное масло'   THEN 'Sesame oil'
  WHEN 'Соевый соус'       THEN 'Soy sauce'
  WHEN 'Васаби'            THEN 'Wasabi'
  WHEN 'Пять специй'       THEN 'Five spice'
  WHEN 'Бадьян'            THEN 'Star anise'
  WHEN 'Шафран'            THEN 'Saffron'
  WHEN 'Песто'             THEN 'Pesto'
  -- Other
  WHEN 'Масло растительное'  THEN 'Vegetable oil'
  WHEN 'Томатная паста'      THEN 'Tomato paste'
  WHEN 'Бульон'              THEN 'Broth'
  WHEN 'Сахар'               THEN 'Sugar'
  WHEN 'Мёд'                 THEN 'Honey'
  WHEN 'Грецкие орехи'       THEN 'Walnuts'
  WHEN 'Миндаль'             THEN 'Almonds'
  WHEN 'Кокосовое молоко'    THEN 'Coconut milk'
  WHEN 'Оливковое масло'     THEN 'Olive oil'
  -- Dairy
  WHEN 'Сливки'              THEN 'Cream'
  WHEN 'Сыр пармезан'        THEN 'Parmesan cheese'
  WHEN 'Моцарелла'           THEN 'Mozzarella'
  WHEN 'Сыр фета'            THEN 'Feta cheese'
  WHEN 'Йогурт'              THEN 'Yogurt'
  -- Cereals
  WHEN 'Мука'                THEN 'Flour'
  WHEN 'Лапша'               THEN 'Noodles'
  WHEN 'Спагетти'            THEN 'Spaghetti'
  WHEN 'Рис жасмин'          THEN 'Jasmine rice'
  WHEN 'Рис арборио'         THEN 'Arborio rice'
  WHEN 'Крупа манная'        THEN 'Semolina'
  WHEN 'Пшено'               THEN 'Millet'
  WHEN 'Перловка'            THEN 'Pearl barley'
  -- Vegetables / legumes
  WHEN 'Фасоль'              THEN 'Beans'
  WHEN 'Чечевица'            THEN 'Lentils'
  WHEN 'Нут'                 THEN 'Chickpeas'
  WHEN 'Авокадо'             THEN 'Avocado'
  WHEN 'Лимон'               THEN 'Lemon'
  WHEN 'Оливки'              THEN 'Olives'
  WHEN 'Руккола'             THEN 'Arugula'
  WHEN 'Грибы'               THEN 'Mushrooms'
  WHEN 'Кинза'               THEN 'Cilantro'
  WHEN 'Тофу'                THEN 'Tofu'
  ELSE NULL
END;
