-- Добавить колонку cuisines и вставить дополнительные ингредиенты (специи и др.).
-- Выполнить в Supabase Dashboard → SQL Editor после создания таблицы ingredients.

ALTER TABLE ingredients
  ADD COLUMN IF NOT EXISTS cuisines TEXT[] DEFAULT '{}';

CREATE INDEX IF NOT EXISTS idx_ingredients_cuisines ON ingredients USING GIN (cuisines);

UPDATE ingredients SET cuisines = '{}' WHERE cuisines IS NULL;

INSERT INTO ingredients (name, category, image_url, cuisines) VALUES
('Лавровый лист', 'spices', NULL, '{}'),
('Паприка', 'spices', NULL, '{}'),
('Кориандр', 'spices', NULL, '{}'),
('Тмин', 'spices', NULL, '{}'),
('Куркума', 'spices', NULL, '{}'),
('Имбирь', 'spices', NULL, '{}'),
('Орегано', 'spices', NULL, '{}'),
('Базилик', 'spices', NULL, '{}'),
('Тимьян', 'spices', NULL, '{}'),
('Розмарин', 'spices', NULL, '{}'),
('Мускатный орех', 'spices', NULL, '{}'),
('Корица', 'spices', NULL, '{}'),
('Гвоздика', 'spices', NULL, '{}'),
('Ваниль', 'spices', NULL, '{}'),
('Карри', 'spices', NULL, '{}'),
('Перец чили', 'spices', NULL, '{}'),
('Красный перец', 'spices', NULL, '{}'),
('Горчица', 'spices', NULL, '{}'),
('Уксус', 'spices', NULL, '{}'),
('Лимонный сок', 'spices', NULL, '{}'),
('Цедра лимона', 'spices', NULL, '{}'),
('Хмели-сунели', 'spices', NULL, '{russian}'),
('Укроп сушёный', 'spices', NULL, '{russian}'),
('Мята', 'spices', NULL, '{}'),
('Кунжут', 'spices', NULL, '{}'),
('Кунжутное масло', 'spices', NULL, '{asian}'),
('Соевый соус', 'spices', NULL, '{asian}'),
('Васаби', 'spices', NULL, '{asian}'),
('Пять специй', 'spices', NULL, '{asian}'),
('Бадьян', 'spices', NULL, '{}'),
('Шафран', 'spices', NULL, '{}'),
('Томатная паста', 'other', NULL, '{}'),
('Бульон', 'other', NULL, '{}'),
('Сливки', 'dairy', NULL, '{}'),
('Сыр пармезан', 'dairy', NULL, '{italian}'),
('Моцарелла', 'dairy', NULL, '{italian}'),
('Сыр фета', 'dairy', NULL, '{}'),
('Йогурт', 'dairy', NULL, '{}'),
('Мука', 'cereals', NULL, '{}'),
('Сахар', 'other', NULL, '{}'),
('Мёд', 'other', NULL, '{}'),
('Грецкие орехи', 'other', NULL, '{}'),
('Миндаль', 'other', NULL, '{}'),
('Кокосовое молоко', 'other', NULL, '{asian}'),
('Фасоль', 'vegetables', NULL, '{}'),
('Чечевица', 'vegetables', NULL, '{}'),
('Нут', 'vegetables', NULL, '{asian}'),
('Авокадо', 'vegetables', NULL, '{}'),
('Лимон', 'vegetables', NULL, '{}'),
('Оливки', 'vegetables', NULL, '{italian}'),
('Руккола', 'vegetables', NULL, '{italian}'),
('Грибы', 'vegetables', NULL, '{}'),
('Лапша', 'cereals', NULL, '{asian}'),
('Спагетти', 'cereals', NULL, '{italian}'),
('Песто', 'spices', NULL, '{italian}'),
('Оливковое масло', 'other', NULL, '{italian}'),
('Кинза', 'vegetables', NULL, '{asian}'),
('Рис жасмин', 'cereals', NULL, '{asian}'),
('Рис арборио', 'cereals', NULL, '{italian}'),
('Крупа манная', 'cereals', NULL, '{russian}'),
('Пшено', 'cereals', NULL, '{russian}'),
('Перловка', 'cereals', NULL, '{russian}'),
('Тофу', 'vegetables', NULL, '{asian}')
ON CONFLICT (name) DO NOTHING;
