-- Колонка кухонь: пустой массив = ингредиент для всех кухонь, иначе только для перечисленных
ALTER TABLE ingredients
  ADD COLUMN IF NOT EXISTS cuisines TEXT[] DEFAULT '{}';

CREATE INDEX IF NOT EXISTS idx_ingredients_cuisines ON ingredients USING GIN (cuisines);

COMMENT ON COLUMN ingredients.cuisines IS 'Кухни, где часто используется: russian, italian, asian, american. {} = все.';

-- Обновить существующие строки (на случай если колонка уже была без default)
UPDATE ingredients SET cuisines = '{}' WHERE cuisines IS NULL;

-- Дополнительные специи и частые продукты (ON CONFLICT DO NOTHING по name)
INSERT INTO ingredients (name, category, image_url, cuisines) VALUES
-- Специи универсальные
('Лавровый лист', 'spices', NULL, '{}'),
('Паприка', 'spices', NULL, '{}'),
('Кориандр', 'spices', NULL, '{}'),
('Тмин', 'spices', NULL, '{}'),
('Куркума', 'spices', NULL, '{}'),
('Имбирь', 'spices', NULL, '{}'),
('Орегано', 'spices', NULL, '{}'),
('Базилик', 'spices', NULL, '{}'),
('Тимьян', 'spices', NULL, '{}'),
('Розмарин', 'spices', NULL, '{}'),
('Мускатный орех', 'spices', NULL, '{}'),
('Корица', 'spices', NULL, '{}'),
('Гвоздика', 'spices', NULL, '{}'),
('Ваниль', 'spices', NULL, '{}'),
('Карри', 'spices', NULL, '{}'),
('Перец чили', 'spices', NULL, '{}'),
('Красный перец', 'spices', NULL, '{}'),
('Горчица', 'spices', NULL, '{}'),
('Уксус', 'spices', NULL, '{}'),
('Лимонный сок', 'spices', NULL, '{}'),
('Цедра лимона', 'spices', NULL, '{}'),
('Чили перец', 'spices', NULL, '{}'),
('Паприка копчёная', 'spices', NULL, '{}'),
('Хмели-сунели', 'spices', NULL, '{russian}'),
('Укроп сушёный', 'spices', NULL, '{russian}'),
('Петрушка сушёная', 'spices', NULL, '{}'),
('Мята', 'spices', NULL, '{}'),
('Кунжут', 'spices', NULL, '{}'),
('Кунжутное масло', 'spices', NULL, '{asian}'),
('Соевый соус', 'spices', NULL, '{asian}'),
('Рисовый уксус', 'spices', NULL, '{asian}'),
('Васаби', 'spices', NULL, '{asian}'),
('Имбирь маринованный', 'spices', NULL, '{asian}'),
('Пять специй', 'spices', NULL, '{asian}'),
('Бадьян', 'spices', NULL, '{}'),
('Шафран', 'spices', NULL, '{}'),
('Эстрагон', 'spices', NULL, '{}'),
('Майоран', 'spices', NULL, '{}'),
('Чабер', 'spices', NULL, '{}'),
-- Часто используемые продукты
('Томатная паста', 'other', NULL, '{}'),
('Томатный соус', 'other', NULL, '{}'),
('Бульон', 'other', NULL, '{}'),
('Бульон куриный', 'other', NULL, '{}'),
('Бульон овощной', 'other', NULL, '{}'),
('Сливки', 'dairy', NULL, '{}'),
('Творог', 'dairy', NULL, '{russian}'),
('Сыр пармезан', 'dairy', NULL, '{italian}'),
('Моцарелла', 'dairy', NULL, '{italian}'),
('Брынза', 'dairy', NULL, '{russian}'),
('Сыр фета', 'dairy', NULL, '{}'),
('Йогурт', 'dairy', NULL, '{}'),
('Сгущёнка', 'dairy', NULL, '{russian}'),
('Мука', 'cereals', NULL, '{}'),
('Сахар', 'other', NULL, '{}'),
('Мёд', 'other', NULL, '{}'),
('Орехи', 'other', NULL, '{}'),
('Грецкие орехи', 'other', NULL, '{}'),
('Миндаль', 'other', NULL, '{}'),
('Кедровые орехи', 'other', NULL, '{italian,russian}'),
('Кокосовое молоко', 'other', NULL, '{asian}'),
('Кукуруза', 'vegetables', NULL, '{}'),
('Горох', 'vegetables', NULL, '{}'),
('Фасоль', 'vegetables', NULL, '{}'),
('Чечевица', 'vegetables', NULL, '{}'),
('Нут', 'vegetables', NULL, '{asian}'),
('Авокадо', 'vegetables', NULL, '{}'),
('Лайм', 'vegetables', NULL, '{}'),
('Лимон', 'vegetables', NULL, '{}'),
('Чернослив', 'vegetables', NULL, '{russian}'),
('Изюм', 'vegetables', NULL, '{}'),
('Оливки', 'vegetables', NULL, '{italian}'),
('Каперсы', 'vegetables', NULL, '{italian}'),
('Артишок', 'vegetables', NULL, '{italian}'),
('Руккола', 'vegetables', NULL, '{italian}'),
('Спаржа', 'vegetables', NULL, '{}'),
('Грибы', 'vegetables', NULL, '{}'),
('Лапша', 'cereals', NULL, '{asian}'),
('Лапша рисовая', 'cereals', NULL, '{asian}'),
('Спагетти', 'cereals', NULL, '{italian}'),
('Пармезан', 'dairy', NULL, '{italian}'),
('Песто', 'spices', NULL, '{italian}'),
('Бальзамический уксус', 'spices', NULL, '{italian}'),
('Оливковое масло', 'other', NULL, '{italian}'),
('Кетчуп', 'other', NULL, '{american}'),
('Горчица дижонская', 'spices', NULL, '{}'),
('Вустерширский соус', 'spices', NULL, '{american}'),
('Копчёная паприка', 'spices', NULL, '{}'),
('Кинза', 'vegetables', NULL, '{asian}'),
('Лемонграсс', 'spices', NULL, '{asian}'),
('Кокос', 'vegetables', NULL, '{asian}'),
('Рис жасмин', 'cereals', NULL, '{asian}'),
('Рис арборио', 'cereals', NULL, '{italian}'),
('Крупа манная', 'cereals', NULL, '{russian}'),
('Пшено', 'cereals', NULL, '{russian}'),
('Перловка', 'cereals', NULL, '{russian}'),
('Хлеб', 'cereals', NULL, '{}'),
('Сухари', 'cereals', NULL, '{}'),
('Бекон', 'meat', NULL, '{american}'),
('Ветчина', 'meat', NULL, '{}'),
('Индейка', 'meat', NULL, '{}'),
('Рыба', 'meat', NULL, '{}'),
('Лосось', 'meat', NULL, '{}'),
('Креветки', 'meat', NULL, '{asian}'),
('Мидии', 'meat', NULL, '{}'),
('Тофу', 'vegetables', NULL, '{asian}'),
('Темпе', 'vegetables', NULL, '{asian}')
ON CONFLICT (name) DO NOTHING;
